UPDATE -- PALAVRA RESERVADA QUE ATUALIZA INFORMAÇOES
Livros -- NOSSA TABELA QUE SERÁ ALTERADO A INFORMAÇÃO
SET -- SET INICIALIZA A PRIMEIRA ALTERAÇÃO EM NOSSO SQL
Ativo = 0 -- EXPRESSÇAO QUE VAI SER ALTERADA
where -- PALAVRA QUE INICIALIZA AS CONDIÇÕES PARA REALIZAR ESTA ALTERAÇÃO
Id = 
(Select * from Livros order by Id desc
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY)